services:
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: crypto-cloud-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - crypto-cloud-network
  
  postgres:
    build:
      context: ./services/postgres
      dockerfile: Dockerfile
    image: custom-postgres:15
    container_name: crypto-cloud-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

      AIRFLOW_DB_USERNAME: ${AIRFLOW_DB_USERNAME}
      AIRFLOW_DB_PASSWORD: ${AIRFLOW_DB_PASSWORD}
      AIRFLOW_DB_NAME: ${AIRFLOW_DB_NAME}

      HIVE_DB_USER: ${HIVE_DB_USER}
      HIVE_DB_PASSWORD: ${HIVE_DB_PASSWORD}
      HIVE_DB_NAME: ${HIVE_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      # - ./services/postgres/init-scripts:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - crypto-cloud-network

  hive-metastore:
    build:
      context: ./services/hive
      dockerfile: Dockerfile
    image: custom-hive:4.0.0
    container_name: crypto-cloud-hive-metastore
    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: postgres
      HIVE_CUSTOM_CONF_DIR: /opt/hive/conf

      HIVE_DB_USER: ${HIVE_DB_USER}
      HIVE_DB_PASSWORD: ${HIVE_DB_PASSWORD}
      HIVE_DB_NAME: ${HIVE_DB_NAME}
      MINIO_USER: ${MINIO_USER}
      MINIO_PASSWORD: ${MINIO_PASSWORD}
      DATA_LAKE_BUCKET: ${DATA_LAKE_BUCKET}
    depends_on:
      - postgres
      - minio
    ports:
      - "9083:9083"
    networks:
      - crypto-cloud-network

  # clickhouse:
  #   image: clickhouse/clickhouse-server:25.8
  #   container_name: crypto-cloud-clickhouse
  #   environment:
  #     CLICKHOUSE_DB: ${CLICKHOUSE_DB}
  #     CLICKHOUSE_USER: ${CLICKHOUSE_USER}
  #     CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
  #   ports:
  #     - "8123:8123"
  #     - "9100:9000"
  #   volumes:
  #     - clickhouse_data:/var/lib/clickhouse
  #   networks:
  #     - crypto-cloud-network


volumes:
  minio_data:
  postgres_data:
  clickhouse_data:

networks:
  crypto-cloud-network:
    external: true