services:
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./services/postgres/init-scripts:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

  hive-metastore:
    image: custom-hive:4.0.1
    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: postgres
      SERVICE_OPTS: >
        -Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgres:5432/metastore_db -Djavax.jdo.option.ConnectionUserName=hive -Djavax.jdo.option.ConnectionPassword=hive
    depends_on:
      - postgres
      - minio
    ports:
      - "9083:9083"
    volumes:
      - hive_warehouse:/opt/hive/data/warehouse

  clickhouse:
    image: clickhouse/clickhouse-server:25.5.1
    environment:
      CLICKHOUSE_DB: testdb
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: 123456
    ports:
      - "8123:8123"
      - "9100:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse

volumes:
  minio_data:
  hive_warehouse:
  postgres_data:
  clickhouse_data:
